var consultores=[
    // Myrna Ojeda
    {show:"myrnaojeal",
    namelg: "Mtra. Myrna Ojeda Álvarez",
    namesm: "Myrna Ojeda",
     img: "../../imgs/Equipo/myrna.png",
     prof: "Consultora en Ciencias Sociales y Acoso Callejero",
     description: "Licenciada en Letras Hispánicas, Maestra en Ciencias del Lenguaje y candidata a Doctora en Ciencias Sociales. Investigadora especialista en análisis del discurso (hermenéutica crítica) con énfasis en violencia de género y resistencias de mujeres."},
    // Regidora María
     {show:"mariagomrue",
     namelg: "María Gómez Rueda",
     namesm: "María Gómez",
     img: "../../imgs/Equipo/regidora.png",
     prof: "Regidora de DDHH e Igualdad de Género de Zapopan",
     description: "Regidora de DDHH e Igualdad de Género de Zapopan. Especialista en Odontopediatría y académica en la Universidad de Guadalajara."},
    // Daniela Bocanegra
     {show:"danielaboctol",
     namelg: "Daniela Bocanegra Toledo",
     namesm: "Daniela Bocanegra",
     img: "../../imgs/Equipo/daniela.png",
     prof:"Especialista en Estudios de Género",
     description: "Politóloga y Especialista en Estudios de Género"},
    //  Giovanni
    {show:"giovannilopram",
    namelg: "Giovanni Daniel López Ramírez",
    namesm:"Giovanni López",
    img: "../../imgs/Equipo/giovanni.png",
    prof:"Consultor en Seguridad Pública y Derechos Humanos",
    description: "Estudiante de derecho en la Universidad de Guadalajara y activista por los Derechos Humanos."},
    // Janis
     {show:"jannettedam",
     namelg: "Jannette Damián",
     namesm:"Jannette Damián",
     img: "../../imgs/Equipo/perfil.png",
     prof:"Mentora y Consultora en Grupos Vulnerados",
     description: "Estudiante de derecho en la Universidad de Guadalajara y activista por los Derechos Humanos."},
    // Fer
     {show:"fernandogom",
     namelg: "Fernando Gómez",
     namesm: "Fernando Gómez",
     img: "../../imgs/Equipo/perfil.png",
     prof:"Mentor y Consultor en Desarrollo Web",
     description: "Estudiante de derecho en la Universidad de Guadalajara y activista por los Derechos Humanos."},
    // Hatziri
     {show:"hatziripar",
     namelg: "Hatziri Parra",
     namesm:"Hatziri Parra",
     img: "../../imgs/Equipo/hatziri.png",
     prof:"Consultora de Marketing",
     description: "Emprendedora y estudiante de Creación y Desarrollo de Empresas en el Tecnológico de Monterrey."},
    // Mónica Perales
     {show:"monicaper",
     namelg: "Mónica Perales",
     namesm: "Mónica Perales",
     img: "../../imgs/Equipo/moni.png",
     prof: "Consultora en psicología con perspectiva de género",
     description: "Estudiante de derecho en la Universidad de Guadalajara y activista por los Derechos Humanos."},
    // Paulette
     {show:"paulette",
     namelg: "Paulette",
     namesm:"Paulette",
     img: "../../imgs/Equipo/perfil.png",
     prof:"Consultora en Derecho",
     description: "?"},
     {show:"jesusmed",
     namelg: "Jesús Medina",
     namesm:"Jesús Medina",
     img: "../../imgs/Equipo/perfil.png",
     prof:"Creador de Senderos Seguros",
     description: "?"}]
    
module.exports=consultores;